# Generated by Django 4.1.5 on 2023-02-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_summary',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
