# Generated by Django 4.1.5 on 2023-02-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
