# Generated by Django 4.1.5 on 2023-02-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_user_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
