# Generated by Django 4.1.5 on 2023-02-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomments',
            name='change',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articlecomments',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articlelikes',
            name='change',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articlelikes',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
