# Generated by Django 4.1.5 on 2023-02-22 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_articleviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleviews',
            name='article_views_article_id_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.articles'),
        ),
    ]
