# Generated by Django 4.1.5 on 2023-02-22 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_alter_articleviews_article_views_article_id_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomments',
            name='article_comments_article_id_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.articles'),
        ),
        migrations.AlterField(
            model_name='articlelikes',
            name='article_likes_article_id_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.articles'),
        ),
    ]
