# Generated by Django 4.1.5 on 2023-08-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='article_user_id_fk',
            new_name='user_id_fk',
        ),
    ]
